"""TMDB adapter constants."""

from __future__ import annotations

from typing import Final

DEFAULT_TMDB_LANGUAGE: Final[str] = "ko-KR"
UNKNOWN_TMDB_LANGUAGE: Final[str] = "und"

TMDB_MIN_INTERVAL_ENV: Final[str] = "ANIVAULT_TMDB_MIN_INTERVAL"
TMDB_MIN_INTERVAL_DEFAULT: Final[str] = "0.05"

TMDB_SEARCH_CACHE_TTL_OK_DAYS: Final[int] = 7
TMDB_SEARCH_CACHE_TTL_EMPTY_DAYS: Final[int] = 1
TMDB_LOCAL_CANDIDATE_LIMIT: Final[int] = 10

TMDB_POSTER_MAX_WORKERS_ENV: Final[str] = "ANIVAULT_POSTER_MAX_WORKERS"
TMDB_POSTER_MAX_WORKERS_DEFAULT: Final[int] = 4
TMDB_POSTER_MAX_WORKERS_MIN: Final[int] = 1
TMDB_POSTER_MAX_WORKERS_MAX: Final[int] = 8

TMDB_POSTER_DOWNLOAD_RETRIES_ENV: Final[str] = "ANIVAULT_POSTER_DOWNLOAD_RETRIES"
TMDB_POSTER_DOWNLOAD_RETRIES_DEFAULT: Final[int] = 3
TMDB_POSTER_DOWNLOAD_RETRIES_MIN: Final[int] = 1

TMDB_POSTER_USER_AGENT: Final[str] = "AniVault/2 (poster cache)"
TMDB_POSTER_HTTP_TIMEOUT_SECONDS: Final[int] = 60
TMDB_POSTER_RETRY_BASE_DELAY_SECONDS: Final[float] = 0.2
TMDB_POSTER_RETRY_JITTER_SECONDS: Final[float] = 0.05
